name: Docker Image CI

on:
  push:
    branches: [ master, dev-1 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bbci-v5:$(date +%s)
